//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNGlutinator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PNGlutinator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add some files to be processed first.
        /// </summary>
        public static string Add_files {
            get {
                return ResourceManager.GetString("Add_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete: Original file copied.
        /// </summary>
        public static string Complete_Original_file_copied {
            get {
                return ResourceManager.GetString("Complete_Original_file_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete: {0} used.
        /// </summary>
        public static string Complete_used {
            get {
                return ResourceManager.GetString("Complete_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image could not be loaded.
        /// </summary>
        public static string Image_could_not_be_loaded {
            get {
                return ResourceManager.GetString("Image_could_not_be_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output directory.
        /// </summary>
        public static string Invalid_output_directory {
            get {
                return ResourceManager.GetString("Invalid_output_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files in batch.
        /// </summary>
        public static string No_files {
            get {
                return ResourceManager.GetString("No_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory does not exist.
        /// </summary>
        public static string Output_directory_does_not_exist {
            get {
                return ResourceManager.GetString("Output_directory_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing complete. {0} files processed..
        /// </summary>
        public static string Processing_complete {
            get {
                return ResourceManager.GetString("Processing_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output directory to continue.
        /// </summary>
        public static string Select_output_directory {
            get {
                return ResourceManager.GetString("Select_output_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trans {
            get {
                object obj = ResourceManager.GetObject("trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
